### PR TITLE
Software design updates

### PR DESCRIPTION
**Pull request by John0b1000**
Updated the software design documents (PlantUML source code) to reflect current architecture.

Renamed some class variables to be more descriptive and to use dunder notation (if private).

Added the interface for the SolarSensorDecoder module and wrote skeleton code in main.py for implementation.

Unit tests all pass for the QuadCellDecoder module. 

Need to verify that all changes will work on the Pi before merging.

### CODE REVIEW

**Comment by JonathanI19** [comment]
Taking a look at this now. Probably won't merge until tmr morning tho

**Comment by JonathanI19** [comment]
@John0b1000 Out of curiosity, how many bits is the adc we're using?

**Comment by John0b1000** [comment]
Arduino has 10-bit ADC (0-1023 range). No rush on the merge

**Review by JonathanI19 — APPROVED** [review]
This looks good to me. Thanks for cleaning it up.

**Comment by JonathanI19** [comment]
@John0b1000 you need to approve it too before we can merge. It looks good on my end tho.

**Pull request merged**
